import * as THREE from 'three';
import {GLTFLoader} from '../vendor/three/addons/loaders/GLTFLoader.js';
import {clone as cloneSkeleton} from '../vendor/three/addons/utils/SkeletonUtils.js';

const api=window.__watchtower;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const forceFallback=new URLSearchParams(location.search).has('no3d');
const loader=new GLTFLoader();
const assetRoot='assets/3d/';
const modelFiles={ash:'lis.gltf',taro:'matt.gltf',noa:'sam.gltf',mei:'shaun.gltf',enemy:'zombie.gltf',brute:'zombie_chubby.gltf'};
const roleModels={assault:'matt.gltf',control:'lis.gltf',support:'sam.gltf'};
const dossiers=[
 {id:'ash',name:'艾許',role:'狙擊',basic:'遠距點射｜優先處決近塔目標',active:'獵殺標記｜小範圍高傷',passive:'穩線射手｜敵人越近傷害越高',upgrade:'升級提高單發火力與技能倍率'},
 {id:'taro',name:'太郎',role:'重裝／壓制',basic:'壓制掃射｜穩定面傷與後座回饋',active:'集中齊射｜壓垮重裝熱源',passive:'重物獵手｜對重裝額外傷害',upgrade:'升階縮短射擊間隔'},
 {id:'noa',name:'諾亞',role:'工程／控制',basic:'電弧扳機｜牽制最近敵群',active:'干擾脈衝｜範圍減速',passive:'模組共用｜降低首次召集費',upgrade:'升級擴大控場半徑'},
 {id:'mei',name:'梅',role:'醫療／修復',basic:'護衛短點｜補足隊伍火力',active:'急救訊標｜修復塔芯並傷敵',passive:'止血程序｜提高修復量',upgrade:'升星提高修復與技能冷卻'}
];
const cache=new Map();
const load=url=>cache.has(url)?cache.get(url):(cache.set(url,loader.loadAsync(assetRoot+url)),cache.get(url));
const fit=(obj,height=2)=>{const box=new THREE.Box3().setFromObject(obj),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());obj.position.sub(center);obj.position.y+=size.y/2;obj.scale.setScalar(height/Math.max(.01,size.y));};
const makeRenderer=canvas=>{const r=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(devicePixelRatio,1.6));r.outputColorSpace=THREE.SRGBColorSpace;r.shadowMap.enabled=false;return r};
const lights=scene=>{scene.add(new THREE.HemisphereLight(0xd9cfad,0x19211e,2.4));const sun=new THREE.DirectionalLight(0xffc56b,2.2);sun.position.set(4,7,3);scene.add(sun)};
const play=(mixer,clips,name,loop=true)=>{const clip=THREE.AnimationClip.findByName(clips,name)||clips[0];if(!clip)return null;const action=mixer.clipAction(clip);action.reset().setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1).play();if(!loop)action.clampWhenFinished=true;return action};

class Battle3D{
 constructor(host){this.host=host;this.canvas=document.createElement('canvas');this.canvas.className='v8-battle-canvas';host.prepend(this.canvas);this.status=document.createElement('div');this.status.className='v8-field-status';this.status.textContent='3-LANE LIVE FEED // LOADING';host.append(this.status);this.scene=new THREE.Scene();this.scene.fog=new THREE.Fog(0x0b1110,9,23);this.camera=new THREE.PerspectiveCamera(38,1,.1,60);this.camera.position.set(7.8,8.8,10.5);this.camera.lookAt(0,0,-1.5);this.renderer=makeRenderer(this.canvas);lights(this.scene);this.clock=new THREE.Clock();this.units=[];this.enemies=new Map();this.shots=[];this.lastFire=new Map();this.setupField();this.loadUnits();this.loop()}
 setupField(){const ground=new THREE.Mesh(new THREE.PlaneGeometry(12,19),new THREE.MeshStandardMaterial({color:0x171d1a,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.z=-2.4;this.scene.add(ground);for(const x of[-2.5,0,2.5]){const lane=new THREE.Mesh(new THREE.PlaneGeometry(1.65,15),new THREE.MeshStandardMaterial({color:0x28302a,roughness:1}));lane.rotation.x=-Math.PI/2;lane.position.set(x,.012,-2.8);this.scene.add(lane);for(let z=-9;z<5;z+=2){const mark=new THREE.Mesh(new THREE.BoxGeometry(.07,.03,.45),new THREE.MeshBasicMaterial({color:0x9b7a3c}));mark.position.set(x,.035,z);this.scene.add(mark)}}const wall=new THREE.Mesh(new THREE.BoxGeometry(8,1.2,1),new THREE.MeshStandardMaterial({color:0x303936,metalness:.5,roughness:.8}));wall.position.set(0,.6,4.5);this.scene.add(wall);const core=new THREE.Mesh(new THREE.CylinderGeometry(.45,.65,2,8),new THREE.MeshStandardMaterial({color:0x4b3a1b,emissive:0x9f5f08,emissiveIntensity:1.4}));core.position.set(0,1.6,4.4);this.scene.add(core);for(const x of[-3.7,3.7]){const tower=new THREE.Mesh(new THREE.CylinderGeometry(.45,.7,3,6),new THREE.MeshStandardMaterial({color:0x313b37,metalness:.6}));tower.position.set(x,1.5,4.25);this.scene.add(tower)}}
 async loadUnits(){try{const s=api.state(),ids=s.team.slice(0,3);for(let i=0;i<ids.length;i++){const id=ids[i],file=modelFiles[id]||roleModels[(s.owned[id]&&s.owned[id].discipline)||'assault']||'lis.gltf',g=await load(file),obj=cloneSkeleton(g.scene);fit(obj,2.1);obj.position.set([-2.5,0,2.5][i],0,3.2);obj.rotation.y=Math.PI;this.scene.add(obj);const mixer=new THREE.AnimationMixer(obj);play(mixer,g.animations,'Idle_Gun');this.units.push({id,obj,mixer,clips:g.animations})}this.status.textContent='3-LANE LIVE FEED // MODELS READY'}catch(e){this.fail('角色模型載入失敗，戰鬥規則仍可操作。',e)}}
 async addEnemy(e){try{const g=await load(e.kind==='brute'?modelFiles.brute:modelFiles.enemy),obj=cloneSkeleton(g.scene);fit(obj,e.kind==='brute'?1.9:1.55);this.scene.add(obj);const mixer=new THREE.AnimationMixer(obj);play(mixer,g.animations,e.kind==='runner'?'Run':'Walk');this.enemies.set(e.id,{obj,mixer,clips:g.animations,hp:e.hp})}catch(err){this.fail('敵人模型載入失敗，已保留戰鬥 HUD。',err)}}
 fire(from,to){if(reduced)return;const geo=new THREE.BufferGeometry().setFromPoints([from,to]),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xffc04a,transparent:true,opacity:1}));this.scene.add(line);this.shots.push({line,life:.12})}
 sync(dt){const s=api.state(),t=s.tactical||{},seen=new Set();(t.enemies||[]).forEach(e=>{seen.add(e.id);if(!this.enemies.has(e.id))this.addEnemy(e);const v=this.enemies.get(e.id);if(!v)return;const lane=e.x<.38?-2.5:e.x>.62?2.5:0;v.obj.position.set(lane,0,-8.2+e.pos*12);if(e.hp<v.hp){const hit=play(v.mixer,v.clips,'HitReact',false);if(hit){setTimeout(()=>play(v.mixer,v.clips,'Walk'),260)}v.hp=e.hp}});for(const[id,v]of this.enemies)if(!seen.has(id)){play(v.mixer,v.clips,'Death',false);setTimeout(()=>{this.scene.remove(v.obj);this.enemies.delete(id)},reduced?0:350)}this.units.forEach((u,i)=>{const state=t.formation?.[i];if(state&&state._fireAt&&this.lastFire.get(i)!==state._fireAt){this.lastFire.set(i,state._fireAt);u.obj.position.z-=.15;if(!reduced)setTimeout(()=>u.obj.position.z+=.15,110);const target=[...this.enemies.values()].sort((a,b)=>b.obj.position.z-a.obj.position.z)[0];if(target)this.fire(u.obj.position.clone().add(new THREE.Vector3(0,1.25,-.3)),target.obj.position.clone().add(new THREE.Vector3(0,1,0)))}});this.status.textContent=`3-LANE // WAVE ${t.wave||0}/10 // ${String(t.phase||'BRIEFING').toUpperCase()}`;for(const v of this.enemies.values())v.mixer.update(dt);for(const u of this.units)u.mixer.update(dt);for(const x of this.shots){x.life-=dt;x.line.material.opacity=Math.max(0,x.life/.12)}this.shots.filter(x=>x.life<=0).forEach(x=>this.scene.remove(x.line));this.shots=this.shots.filter(x=>x.life>0)}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(this.canvas.width!==Math.round(w*this.renderer.getPixelRatio())||this.canvas.height!==Math.round(h*this.renderer.getPixelRatio())){this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}}
 loop(){if(!this.host.isConnected){this.renderer.dispose();return}requestAnimationFrame(()=>this.loop());const dt=Math.min(.05,this.clock.getDelta());this.resize();this.sync(dt);this.renderer.render(this.scene,this.camera)}
 fail(msg,e){console.warn('[v8 fallback]',e);this.status.textContent='2D FALLBACK // GAMEPLAY ACTIVE';if(!this.host.querySelector('.v8-error')){const n=document.createElement('div');n.className='v8-error';n.textContent=msg;this.host.append(n)}}
}

class Preview3D{
 constructor(host){this.host=host;this.canvas=host.querySelector('canvas');this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(35,1,.1,50);this.camera.position.set(0,1.55,5.4);this.renderer=makeRenderer(this.canvas);lights(this.scene);this.clock=new THREE.Clock();this.current=null;this.drag=false;this.angle=0;this.bind();this.show('ash');this.loop()}
 bind(){this.canvas.addEventListener('pointerdown',e=>{this.drag=true;this.x=e.clientX;this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(this.drag){this.angle+=(e.clientX-this.x)*.012;this.x=e.clientX}});this.canvas.addEventListener('pointerup',()=>this.drag=false)}
 async show(id){try{const g=await load(modelFiles[id]),obj=cloneSkeleton(g.scene);fit(obj,2.7);if(this.current)this.scene.remove(this.current.obj);const mixer=new THREE.AnimationMixer(obj);play(mixer,g.animations,'Idle_Gun');this.current={obj,mixer};this.scene.add(obj)}catch(e){this.host.innerHTML='<div class="v8-fallback">3D 預覽載入失敗。角色資料與編隊功能仍可使用。</div>';console.warn('[v8 preview fallback]',e)}}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(this.canvas.width!==Math.round(w*this.renderer.getPixelRatio())||this.canvas.height!==Math.round(h*this.renderer.getPixelRatio())){this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}}
 loop(){if(!this.host.isConnected){this.renderer.dispose();return}requestAnimationFrame(()=>this.loop());const dt=Math.min(.05,this.clock.getDelta());this.resize();if(this.current){if(!this.drag&&!reduced)this.angle+=dt*.35;this.current.obj.rotation.y=this.angle;this.current.mixer.update(dt)}this.renderer.render(this.scene,this.camera)}
}

let battle=null,preview=null,selected='ash';
function dossierMarkup(){const d=dossiers.find(x=>x.id===selected);return `<section class="v8-dossier" aria-label="四角色 3D 戰術檔案"><header class="v8-dossier-head"><div><div class="label">CREW DOSSIER // 04</div><h2>${d.name}・${d.role}</h2></div><span class="utility">LOCAL 3D</span></header><div class="v8-model-stage"><canvas class="v8-preview-canvas" aria-label="${d.name} 3D 人物，可左右拖曳旋轉"></canvas></div><div class="v8-roster">${dossiers.map(x=>`<button data-v8-hero="${x.id}" aria-selected="${x.id===selected}">${x.name}<br>${x.role}</button>`).join('')}</div><div class="v8-role-data"><div><b>普通攻擊</b><span>${d.basic}</span></div><div><b>主動技能</b><span>${d.active}</span></div><div><b>被動特性</b><span>${d.passive}</span></div><div><b>成長回饋</b><span>${d.upgrade}</span></div></div></section>`}
function enhance(){const field=document.querySelector('.view.active .battlefield');if(field&&!field.querySelector('.v8-battle-canvas,.v8-fallback')){if(forceFallback||(!document.createElement('canvas').getContext('webgl2')&&!document.createElement('canvas').getContext('webgl'))){const n=document.createElement('div');n.className='v8-fallback';n.textContent='3D 無法啟用，已切換可操作的戰術 HUD。';field.prepend(n)}else battle=new Battle3D(field)}const heroView=document.querySelector('.view.active');if(api.state().tab==='heroes'&&heroView&&!heroView.querySelector('.v8-dossier')){heroView.insertAdjacentHTML('afterbegin',dossierMarkup());if(!forceFallback)preview=new Preview3D(heroView.querySelector('.v8-model-stage'));else heroView.querySelector('.v8-model-stage').innerHTML='<div class="v8-fallback">3D 預覽已停用；角色資料與編隊功能仍可使用。</div>'}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-v8-hero]');if(!b)return;selected=b.dataset.v8Hero;const card=b.closest('.v8-dossier');card.outerHTML=dossierMarkup();preview=new Preview3D(document.querySelector('.v8-model-stage'))});
new MutationObserver(enhance).observe(document.getElementById('game'),{childList:true,subtree:true});
enhance();
window.__watchtowerV8={version:8,assets:[...Object.values(modelFiles)],dossiers,webgl:!forceFallback&&!!document.createElement('canvas').getContext('webgl'),forceFallback};
